logging:
  file: logs/application.log
  #  pattern:
  #    console: "%d %-5level %logger : %msg%n"
  #    file: "%d %-5level [%thread] %logger : %msg%n"
  #  level:
  #    org.springframework.web: DEBUG
  http:
    request: true
    response: false